apiVersion: v1
kind: Namespace
metadata:
  name: lkey09211-dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lkey09211-dev
data:
  KAFKA_BOOTSTRAP: "kafka:9092"
  INTERESTING_TOPIC: "interesting"
  NOT_INTERESTING_TOPIC: "not_interesting"
  MONGO_URI: "mongodb://mongo:27017"
  MONGO_DB: "newsdb"
  COLL_INTERESTING: "interesting_messages"
  COLL_NOT_INTERESTING: "not_interesting_messages"
