apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-api
  namespace: lkey09211-dev
spec:
  replicas: 1
  selector: { matchLabels: { app: publisher-api } }
  template:
    metadata: { labels: { app: publisher-api } }
    spec:
      containers:
        - name: publisher-api
          image: REPLACE_WITH_YOUR_IMAGE/publisher-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: { name: app-config }
---
apiVersion: v1
kind: Service
metadata:
  name: publisher-api
  namespace: lkey09211-dev
spec:
  selector: { app: publisher-api }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: publisher-api
  namespace: lkey09211-dev
spec:
  to: { kind: Service, name: publisher-api }
  port: { targetPort: http }
  tls: { termination: edge }
